src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpKernel\Log\Logger;
use Symfony\Component\Validator\Constraints\PositiveOrZero;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Journey $journey = null;

    #[ORM\Column(type: Types::INTEGER)]
    #[PositiveOrZero()]
    private ?int $numStartingArea = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'games')]
    private ?User $user = null;

    #[ORM\OneToOne(inversedBy: 'game', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?OngoingChallenge $ongoingChallenge = null;

    #[ORM\Column]
    private bool $isFinished = false;

    #[ORM\Column]
    private ?int $numberOfAreasCompleted = null;

    #[ORM\Column]
    private ?int $numberOfAreas = null;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getJourney(): ?Journey
    {
        return $this->journey;
    }

    public function setJourney(?Journey $journey): static
    {
        $this->journey = $journey;

        return $this;
    }

    public function getNumStartingArea(): ?int
    {
        return $this->numStartingArea;
    }

    public function setNumStartingArea(?int $numStartingArea): static
    {
        $this->numStartingArea = $numStartingArea;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function isFinished(): bool
    {
        return $this->isFinished;
    }

    public function setIsFinished(bool $isFinished): static
    {
        $this->isFinished = $isFinished;

        return $this;
    }

    public function getNumberOfAreasCompleted(): ?int
    {
        return $this->numberOfAreasCompleted;
    }

    public function setNumberOfAreasCompleted(int $numberOfAreasCompleted): static
    {
        $this->numberOfAreasCompleted = $numberOfAreasCompleted;

        return $this;
    }

    public function getNumberOfAreas(): ?int
    {
        return $this->numberOfAreas;
    }

    public function setNumberOfAreas(int $numberOfAreas): static
    {
        $this->numberOfAreas = $numberOfAreas;

        return $this;
    }

    public function getOngoingChallenge(): ?OngoingChallenge
    {
        return $this->ongoingChallenge;
    }

    public function setOngoingChallenge(OngoingChallenge $ongoingChallenge): static
    {
        $this->ongoingChallenge = $ongoingChallenge;

        return $this;
    }

    public function getNextArea() : Area
    {
        // Augmente le nombre de zones complétées
        $this->setNumberOfAreasCompleted($this->getNumberOfAreasCompleted() + 1);

        // Récupère la zone suivante dans l'ordre du parcours
        $newAreaNumber = ($this->getNumStartingArea() + $this->getNumberOfAreasCompleted()) % $this->getNumberOfAreas();

        return $this->journey->getAreas()->get($newAreaNumber);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\DTO\HotspotDTO;
use App\DTO\OngoingChallengeDTO;
use App\DTO\OngoingGameDTO;
use App\DTO\ScannedSpeciesDTO;
use App\Entity\Area;
use App\Entity\Game;
use App\Entity\Journey;
use App\Entity\Species;
use App\Entity\User;
use App\Repository\AreaRepository;
use App\Repository\GameRepository;
use App\Repository\JourneyRepository;
use App\Repository\SpeciesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;

final class GameController extends AbstractController
{
    public function __construct(private readonly EntityManagerInterface $entityManager)
    {
    }

    #[Route('/parties', name: 'games')]
    public function games(GameRepository $gameRepository): Response
    {

        $isConnected = false;
        $games = [];

        /**
         * @var $user User
         */
        $user = $this->getUser();
        if ($user !== null) {
            $games = $gameRepository->findByUser($user);
            $isConnected = true;
        }

        $ongoingGames = array_map(function (Game $g): OngoingGameDTO {
            $gameFinished = $g->isFinished();

            if ($gameFinished) {
                $title = "Terminé : ";
            }else {
                $title = "Zone " . $g->getNumberOfAreasCompleted()+1 . "/" . $g->getNumberOfAreas() .
                    " \"";
            }

            $title = $title .
                $g->getOngoingChallenge()->getChallenge()->getArea()->getTitle() .
                "\" - " .
                ($g->getUpdatedAt() ? $g->getUpdatedAt()->format("d/m/Y") : "Date inconnue")
            ;

            return new OngoingGameDTO(
                title: $title,
                gameID: $g->getId(),
                isFinished: $g->isFinished()
            );
        }, $games);

        return $this->render('game/games.html.twig', [
            "connected" => $isConnected,
            "games" => $ongoingGames
        ]);
    }

    #[Route('/selectionner-zone', name: 'select_area')]
    public function select_area(JourneyRepository $journeyRepository): Response
    {

        /**
         * @var $journey Journey
         */
        $journey = $journeyRepository->findOneBy(["title" => "Le Mystère du Professeur Verdant"]);
        $journeyID = $journey->getId();

        $hotspots = array_map(function (Area $a) {
            return new HotspotDTO(
                lat: $a->getLatGPS(),
                lng: $a->getLngGPS(),
                title: $a->getTitle(),
                areaID: $a->getId()
            );
        }, $journey->getAreas()->toArray());

        return $this->render('game/select_area.html.twig', [
            "journeyID" => $journeyID,
            'hotspots' => $hotspots
        ]);
    }

    #[Route('parcours/{journeyID}/rejoindre-zone/{areaID}', name: 'reach_area', requirements: ['journeyID' => Requirement::DIGITS, 'areaID' => Requirement::DIGITS,])]
    #[Route('/jeu/{gameID}/rejoindre-zone/{areaID}', name: 'play.reach_area', requirements: ['areaID' => "\d+|__areaID__", 'id' => Requirement::DIGITS])]
    public function reach_area(
        string $areaID,
        AreaRepository $areaRepository,
        GameRepository $gameRepository,
        ?string $journeyID = null,
        ?string $gameID = "__gameID__"
    ): Response
    {
        if ($gameID !== "__gameID__") {
            $game = $gameRepository->findOneBy(['id' => $gameID]);

            if (!$game) {
                $this->addFlash("danger", "Partie Introuvable");
                return $this->redirectToRoute('home');
            }

            /**
             * @var $user User
             */
            $user = $this->getUser();

            // Vérification du joueur
            $checkPlay = $this->checkValidPlayer($user, $game);
            if ($checkPlay) {
                return $checkPlay;
            }

            if ($game->isFinished()) {
                $this->addFlash("danger", "Cette partie est terminée");
                return $this->redirectToRoute('home');
            }

            $journeyID = $game->getJourney()->getId();
        }

        /**
         * @var $area Area
         */
        $area = $areaRepository->find($areaID);

        if (!$area) {
            $this->addFlash("danger", "Zone Introuvable");
            return $this->redirectToRoute('home');
        }

        $hotspotDest = new HotspotDTO(
            lat: $area->getLatGPS(),
            lng: $area->getLngGPS()
        );

        /**
         * @var $user User
         */
        $user = $this->getUser();
        $userID = $user ? $user->getId() : -1;

        return $this->render('game/reach_area.html.twig', [
            'hotspotDest' => $hotspotDest,
            'gameID' => $gameID,
            'journeyID' => $journeyID,
            'areaID' => $areaID,
            'userID' => $userID
        ]);
    }

    #[Route('/jeu/{gameID}/', name: 'play', requirements: ['gameID' => '\d+|__gameID__'])]
    public function play(int $gameID, GameRepository $gameRepository): Response
    {

        $game = $gameRepository->findOneBy(['id' => $gameID]);

        if (!$game) {
            $this->addFlash("danger", "Partie Introuvable");
            return $this->redirectToRoute('home');
        }

        /**
         * @var $user User
         */
        $user = $this->getUser();

        // Vérification du joueur
        $checkPlay = $this->checkValidPlayer($user, $game);
        if ($checkPlay) {
            return $checkPlay;
        }

        if ($game->isFinished()) {
            $this->addFlash("danger", "Cette partie est terminée");
            return $this->redirectToRoute('home');
        }

        $scannedSpecies = $game->getOngoingChallenge()->getScannedSpecies();
        $lastScannedSpecies = $scannedSpecies->isEmpty() ? "Aucune espèces scannées" : $scannedSpecies->last()->getLatinName();

        $ongoingChallenge = new OngoingChallengeDTO(
            numberOfAreasCompleted: $game->getNumberOfAreasCompleted(),
            numberOfAreas: $game->getNumberOfAreas(),
            type: $game->getOngoingChallenge()->getChallenge()->getType(),
            description: $game->getOngoingChallenge()->getChallenge()->getDescription(),
            image: $game->getOngoingChallenge()->getChallenge()->getImage(),
            lastHint: $game->getOngoingChallenge()->getLastHintTxt(),
            lastScannedSpecies: $lastScannedSpecies
        );

        return $this->render( 'game/play.html.twig', [
            'ongoingChallenge' => $ongoingChallenge,
            'gameID' => $gameID
        ]);
    }

    #[Route('/jeu/{gameID}/carte', name: 'play.map', requirements: ['gameID' => Requirement::DIGITS])]
    public function map(int $gameID, GameRepository $gameRepository)
    {

        $game = $gameRepository->findOneBy(['id' => $gameID]);

        if (!$game) {
            $this->addFlash("danger", "Partie Introuvable");
            return $this->redirectToRoute('home');
        }

        /**
         * @var $user User
         */
        $user = $this->getUser();

        // Vérification du joueur
        $checkPlay = $this->checkValidPlayer($user, $game);
        if ($checkPlay) {
            return $checkPlay;
        }

        if ($game->isFinished()) {
            $this->addFlash("danger", "Cette partie est terminée");
            return $this->redirectToRoute('home');
        }

        $species = $game->getOngoingChallenge()->getChallenge()->getSpecies()->toArray();

        $areaLat = $game->getOngoingChallenge()->getChallenge()->getArea()->getLatGPS();
        $areaLng = $game->getOngoingChallenge()->getChallenge()->getArea()->getLngGPS();

        $hotspots = array_map(function (Species $s): HotspotDTO {
            return new HotspotDTO(
                lat:$s->getLatGPS(),
                lng:$s->getLngGPS(),
                title: "Espèce n°".$s->getId()
            );
        }, $species);

        return $this->render('game/map.html.twig', [
            'hotspots' => $hotspots,
            'areaLat' => $areaLat,
            'areaLng' => $areaLng,
            'gameID' => $gameID,
        ]);

    }

    #[Route('/jeu/{gameID}/scanner', name: 'play.scanner', requirements: ['gameID' => Requirement::DIGITS])]
    public function scanner(int $gameID, GameRepository $gameRepository): Response
    {
        $game = $gameRepository->findOneBy(['id' => $gameID]);

        if (!$game) {
            $this->addFlash("danger", "Partie Introuvable");
            return $this->redirectToRoute('home');
        }

        /**
         * @var $user User
         */
        $user = $this->getUser();

        // Vérification du joueur
        $checkPlay = $this->checkValidPlayer($user, $game);
        if ($checkPlay) {
            return $checkPlay;
        }

        if ($game->isFinished()) {
            $this->addFlash("danger", "Cette partie est terminée");
            return $this->redirectToRoute('home');
        }

        return $this->render('game/scanner.html.twig', [
            'gameID' => $gameID
        ]);
    }

    #[Route('jeu/{gameID}/informations-espece/{speciesID}', name: 'play.species_information', requirements: ['gameID' => Requirement::DIGITS, 'speciesID' => '\d+|__SPECIESID__'])]
    public function species_information(
        int $gameID,
        int $speciesID,
        SpeciesRepository $speciesRepository,
        GameRepository $gameRepository,
        EntityManagerInterface $entityManager
    ): Response
    {
        $game = $gameRepository->findOneBy(['id' => $gameID]);

        if (!$game) {
            $this->addFlash("danger", "Partie Introuvable");
            return $this->redirectToRoute('home');
        }

        /**
         * @var $user User
         */
        $user = $this->getUser();

        // Vérification du joueur

templates/game/correct_guess.html.twig
{% extends 'base.html.twig' %}

{% block title %}TerraQuest - Jeu{% endblock %}

{% block importLink %}

{% endblock %}

{% block stylesheets %}{% endblock %}

{%  block javascripts %}
    <script>

        document.addEventListener("DOMContentLoaded", function () {

            // Fonction pour gérer l'événement du bouton "Nouvel Indice"
            const newHintButton = document.querySelector("a.btn[data-action='next-area']");
            newHintButton.addEventListener("click", function(event) {
                event.preventDefault();

                const gameID = "{{ gameID }}";

                fetch("{{ path('api.next_area') }}", {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    body: JSON.stringify({ gameID: gameID })
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            // Si la nouvelle zone arrive avec succès, redirige l'utilisateur vers la page pour atteindre la zone en question
                            window.location.href = "{{ path('play.reach_area', {gameID: gameID, areaID: "__areaID__"}) }}".replace("__areaID__", data.message.newAreaID);
                        } else {
                            alert('Erreur lors de la demande d\'indice: ' + data.message);
                        }
                    })
                    .catch(error => {
                        console.error('Erreur:', error);
                        alert('Une erreur est survenue.');
                    });
            });

        });
    </script>
{%  endblock %}

{% block body %}
    <nav class="navbar navbar-dark bg-dark px-5 fixed-top">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('home') }}">Accueil</a>
    </nav>

    <main class="d-flex flex-column justify-content-center align-items-center py-2 px-5 nav-margin-top" style="min-height: 90dvh">
        <div class="d-flex flex-column gap-4">
            <div class="d-flex flex-column justify-content-center align-items-center px-5 gap-3">
                <h2>Bravo !</h2>
                <h3>Vous avez trouvé la bonne espèce !</h3>
            </div>
            <hr class="hr-rounded">
            <div class="d-flex flex-column justify-content-center align-items-center px-5 gap-3">
                <h3>Testez-vous avec un quiz sur cette espèce !</h3>
                <a class="btn btn-primary" href="{{ path('play.quiz', {gameID: gameID}) }}">Quiz</a>
            </div>
            <hr class="hr-rounded">
            <div class="d-flex flex-column justify-content-center align-items-center px-5 gap-3">
                <h3>Passez à la zone suivante</h3>
                <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="#" data-action="next-area">Zone suivante</a>
            </div>
        </div>
    </main>

{% endblock %}

templates/game/games.html.twig
{% extends 'base.html.twig' %}

{% block title %}TerraQuest - Parties{% endblock %}

{% block stylesheets %}

{% endblock %}

{% block body %}
    <nav class="navbar navbar-dark bg-dark px-5 fixed-top">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('home') }}">Retours</a>
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('settings', { tgPath: app.request.uri|url_encode }) }}">Param</a>
    </nav>
    <main class="d-flex flex-column align-items-center gap-2 py-2 px-5 nav-margin-top nav-margin-bottom" style="margin: 5rem auto">
        <h2>Parties</h2>
        {% if connected %}
            <div class="d-flex flex-column justify-content-center align-items-center gap-2">
                {% for game in games %}
                    <a
                            class="btn btn-primary m-0 my-auto text-center align-content-center {{ game.finished ? "disabled" : "" }}"
                            style="width: 400px; min-height: 3rem"
                            href="{{ path('play', {gameID: game.gameID}) }}"
                    >
                        {{ game.title }}
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <div class="d-flex flex-column justify-content-center align-items-center gap-2">
                <a
                    class="btn btn-primary m-0 my-auto text-center align-content-center" style="width: 400px; min-height: 3rem"
                    href="{{ path('app_login', { tgPath: app.request.uri|url_encode }) }}"
                >
                    Connectez-vous pour charger vos parties
                </a>
            </div>

        {% endif %}
    </main>
    <footer class="d-flex justify-content-center bg-dark text-white text-center px-5 py-2 fixed-bottom">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('select_area') }}">Nouvelle Partie</a>
    </footer>
{% endblock %}

templates/game/hints.html.twig
{% extends 'base.html.twig' %}

{% block title %}TerraQuest - Jeu{% endblock %}

{% block importLink %}

{% endblock %}

{% block stylesheets %}

{% endblock %}

{%  block javascripts %}
    <script>

        document.addEventListener("DOMContentLoaded", function () {

            // Fonction pour gérer l'événement du bouton "Nouvel Indice"
            const newHintButton = document.querySelector("a.btn[data-action='new-hint']");
            newHintButton.addEventListener("click", function(event) {
                event.preventDefault();

                const gameID = "{{ gameID }}";

                fetch("{{ path('api.new_hint') }}", {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    body: JSON.stringify({ gameID: gameID })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        // Si l'indice est demandé avec succès, on actualise la page
                        location.reload();
                    } else {
                        alert('Erreur lors de la demande d\'indice: ' + data.message);
                    }
                })
                .catch(error => {
                    console.error('Erreur:', error);
                    alert('Une erreur est survenue.');
                });
            });

        });
    </script>
{% endblock %}

{% block body %}
    <nav class="navbar navbar-dark bg-dark px-5 fixed-top">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('play', {gameID: gameID}) }}">Jeu</a>
    </nav>
    <main class="d-flex flex-column align-items-center gap-4 py-2 px-5 nav-margin-top nav-margin-bottom">
        <div class="d-flex flex-column justify-content-center align-items-center gap-2">
            {% for key,hint in hints|reverse %}
                <div class="d-flex flex-column justify-content-center align-items-center gap-2 card bg-primary p-3" style="width: 60dvw">
                    <h4>Indice n°{{ hints|length - key }}</h4>
                    <h5>{{ hint }}</h5>
                </div>
            {% endfor %}
            {% if hints is empty %}
                <div class="d-flex flex-column justify-content-center align-items-center gap-2 card bg-primary p-4" style="width: 60dvw">
                    <h5>Aucun indice demandé</h5>
                </div>
            {% endif %}
        </div>
    </main>
    <footer class="d-flex justify-content-center bg-dark text-white text-center px-5 py-2 fixed-bottom">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3 {{ hintAvailable ? "" : "disabled" }}" href="#" data-action="new-hint">{{ hintAvailable ? "Nouvel indice" : "Plus aucun indice" }}</a>
    </footer>
{% endblock %}

templates/game/journey_ending.html.twig
{% extends 'base.html.twig' %}

{% block title %}TerraQuest - Jeu{% endblock %}

{% block importLink %}

{% endblock %}

{% block stylesheets %}{% endblock %}

{%  block javascripts %}

{%  endblock %}

{% block body %}
    <nav class="navbar navbar-dark bg-dark px-5 fixed-top">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('home') }}">Accueil</a>
    </nav>

    <main class="d-flex flex-column justify-content-center align-items-center py-2 px-5 nav-margin-top" style="min-height: 90dvh">
        <div class="row align-items-center mb-4">
            <div class="col-md-8 d-flex flex-column align-items-end">
                <div class="d-flex flex-column justify-content-end align-items-center bubble bubble-left">
                    <h4>
                        Félicitations, jeune botaniste ! Tu as trouvé la dernière plante recherchée !<br>
                        <br>
                        Grâce à toi, j’ai enfin retrouvé toutes les informations que j’avais perdues. Ton aide a été précieuse, et je te remercie du fond du cœur pour ta détermination et ton esprit d’aventure.<br>
                        <br>
                        Si tu es encore prêt à relever un dernier défi, voici un derniez quiz !
                    </h4>
                    <a class="btn btn-primary" href="{{ path('play.quiz', {gameID: gameID}) }}">Quiz</a>
                </div>
            </div>
            <div class="col-md-4 d-flex justify-content-start">
                <img src="{{ asset('images/prof-removebg-reverse.png') }}" class="img-fluid" style="width: 25rem; height: 25rem" alt="Professeur">
            </div>
        </div>
    </main>

{% endblock %}

templates/game/map.html.twig
{% extends 'base.html.twig' %}

{% block title %}TerraQuest - Jeu{% endblock %}

{% block importLink %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
{% endblock %}

{% block stylesheets %}{% endblock %}

{%  block javascripts %}
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            setTimeout(function () { // Délai pour s'assurer du chargement complet du DOM
                var center = [ {{ areaLat }} , {{ areaLng }} ];
                var zoom = 19;

                window.map = L.map('map').setView(center, zoom);

                L.tileLayer('https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', {
                    attribution: '&copy; Google Maps',
                    maxZoom: 20
                }).addTo(map);

                function generatePopUp(title) {
                    return title;
                }

                var hotspots = [
                    {% for hotspot in hotspots %}
                    {
                        lat: {{ hotspot.lat }},
                        lng: {{ hotspot.lng }},
                        popup: "{{ hotspot.title }}"
                    },
                    {% endfor %}
                ];

                hotspots.forEach(hotspot => {
                    L.marker([hotspot.lat, hotspot.lng])
                        .addTo(map)
                        .bindPopup(hotspot.popup);
                });

                setTimeout(function () {
                    map.invalidateSize(); // Fixe les problèmes d'affichage
                }, 500);
            }, 100);
        });
    </script>
{%  endblock %}

{% block body %}
    <nav class="navbar navbar-dark bg-dark px-5 fixed-top">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('play', {gameID: gameID}) }}">Jeu</a>
    </nav>

    <main class="d-flex flex-column justify-content-center align-items-center gap-4 py-2 px-5 nav-margin-top" style="min-height: 90dvh">
        <h2>Dirigez-vous vers une espèce de la zone</h2>
        <div class="w-75 h" id="map" style="height: 65dvh"></div>
    </main>

{% endblock %}

templates/game/select_area.html.twig
{% extends 'base.html.twig' %}

{% block title %}TerraQuest - Sélectionner Zone{% endblock %}

{% block importLink %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
{% endblock %}

{% block stylesheets %}{% endblock %}

{%  block javascripts %}
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            setTimeout(function () { // Délai pour s'assurer du chargement complet du DOM
                var center = [47.5013, -0.5700];
                var zoom = 17;

                window.map = L.map('map').setView(center, zoom);

                L.tileLayer('https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', {
                    attribution: '&copy; Google Maps',
                    maxZoom: 20
                }).addTo(map);

                function generatePopUp(title, link) {
                    return "<a class='btn btn-primary text-white' href='" + link + "'>" + title + "</a>";
                }

                var hotspots = [
                    {% for hotspot in hotspots %}
                    {
                        lat: {{ hotspot.lat }},
                        lng: {{ hotspot.lng }},
                        popup: generatePopUp("{{ hotspot.title }}", "{{ path('reach_area', {journeyID: journeyID, areaID: hotspot.areaID}) }}")
                    },
                    {% endfor %}
                ];

                hotspots.forEach(hotspot => {
                    L.marker([hotspot.lat, hotspot.lng])
                        .addTo(map)
                        .bindPopup(hotspot.popup);
                });

                setTimeout(function () {
                    map.invalidateSize(); // Fixe les problèmes d'affichage
                }, 500);
            }, 100);
        });
    </script>
{%  endblock %}

{% block body %}
    <nav class="navbar navbar-dark bg-dark px-5 fixed-top">
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('games') }}">Retour</a>
        <a type="button" class="btn bsb-btn-xl btn-primary gap-3" href="{{ path('games') }}">Param</a>
    </nav>

    <main class="d-flex flex-column justify-content-center align-items-center gap-4 py-2 px-5 nav-margin-top"">
        <h2>Choisissez votre zone</h2>
        <div class="w-75 h" id="map" style="height: 65dvh"></div>
    </main>

{% endblock %}